### ISSUE TITLE
importing video file

### ISSUE THREAD

**Issue by yaqxswcde** [nateraw/animegan-v2-for-videos#1]
Hey, 

first of all it's cool to see someone make a video version of this, already fell in love with the original one :)

It already works with a webcam recording but i can't find a way to import a video file. Does that still need to be added or am i doing something wrong? Tried via Spaces with Chrome.

cheers and cool stuff!

edit: sorry i should probably add that i tried it via HuggingFace, not on my local machine

**Comment by nateraw** [comment]
There's a [notebook](https://github.com/nateraw/animegan-v2-for-videos/blob/main/animegan_v2_for_videos.ipynb) in the Github repo that can be opened in Colab that uses Video files directly 😄
