### ISSUE TITLE
"Open in Colab" button does not work: gradio not found

### ISSUE THREAD

**Issue by surak** [nateraw/animegan-v2-for-videos#2]
When looking at the ipynb file, there's the option to open it in Google Colab. Which won't work, as it won't find the gradio python module.

**Comment by nateraw** [comment]
Did you run the first cell to `pip install gradio`?

**Comment by surak** [comment]
duh- I thought I did.

**Comment by nateraw** [comment]
haha all good! If you run into any other problems please let me know! The notebook may be out of sync of the latest demo in Hugging Face spaces.
